title: Teddy Lack
logo: "/images/image.png?raw=true"
description: >
  <p align="center">
    <a href="pdf/Resume.pdf">CV</a> |
    <a href="https://www.linkedin.com/in/teddy-lack-b02b291bb/">LinkedIn</a> |
    <a href="https://github.com/tlack-create">GitHub</a>
  </p>
  
  <p align="justify">
    I am a Biomedical Sciences graduate from Newcastle University with a year of industrial experience at GSK in regulatory affairs. 
    <br><br>
    After graduating in 2023, I spent time traveling in South-East Asia. I am now seeking a graduate role in analytics, focusing on financial markets.
  </p>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0
