title: Teddy Lack # your name (or website title) here
logo: "/images/image.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <p align="center">
  <a href="pdf/Resume.pdf">CV</a> |
  <a href="https://www.linkedin.com/in/chriskhanhtran/">LinkedIn</a> |
  <a href="https://github.com/tlack-create">GitHub</a>
  </p>
  
  <p align="justify">
  I am a recent Biomedical Sciences (BSc Hons) graduate from Newcastle University.
  <br><br>
  I am currently a looking for a graduate position within analytics with a particular interest in consulting.
  <br><br>
  </p>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
